### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dheerajbred** [JuniperPhoton/MyerSplash.Android#18]
I am getting this error when I run the app. I made no changes

```
2019-09-03 01:26:58.925 1048-1419/com.juniperphoton.myersplash.debug E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.juniperphoton.myersplash.debug, PID: 1048
    java.lang.Error: APIException(code=401, url=https://api.unsplash.com/photos?&page=1&per_page=10, msg=null)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: APIException(code=401, url=https://api.unsplash.com/photos?&page=1&per_page=10, msg=null)
        at com.juniperphoton.myersplash.api.CustomInterceptor.intercept(CustomInterceptor.kt:28)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by JuniperPhoton** [comment]
The unsplash API should be used with a Key, which is a privacy key for you. Please refer to the developer [website](https://unsplash.com/developers) to retrieve your key and add an entry in your `local.properties` file like this:

```
unsplashKey=xxxxx
```
